import type { Service, ServiceCategory } from "@/types";
import { useMemo } from "react";

// ─── 60+ Services across 8 platforms ──────────────────────────────────────────
export const MOCK_SERVICES: Service[] = [
  // ─── Instagram (11) ──────────────────────────────────────────────────────────
  {
    id: "ig-followers",
    name: "Instagram Followers",
    category: "instagram",
    pricePerThousand: 89,
    basicPrice: 89,
    recommendedPrice: 111,
    premiumPrice: 167,
    minOrder: 100,
    maxOrder: 100000,
    deliveryTime: "0–12 hours",
    refill: true,
    rating: 5,
    description: "Real-looking followers with profile pictures.",
    speed: "fast",
    successRate: 98,
    retentionScore: 92,
    refillPolicy: "guaranteed",
    urgencySignal: "🔥 High Demand",
  },
  {
    id: "ig-indian-followers",
    name: "Instagram Indian Followers",
    category: "instagram",
    pricePerThousand: 99,
    basicPrice: 99,
    recommendedPrice: 124,
    premiumPrice: 186,
    minOrder: 100,
    maxOrder: 50000,
    deliveryTime: "1–6 hours",
    refill: true,
    rating: 5,
    description: "Geo-targeted Indian followers for local brands.",
    speed: "fast",
    successRate: 97,
    retentionScore: 90,
    refillPolicy: "guaranteed",
    urgencySignal: "🇮🇳 India Targeted",
  },
  {
    id: "ig-uae-followers",
    name: "Instagram UAE Followers",
    category: "instagram",
    pricePerThousand: 129,
    basicPrice: 129,
    recommendedPrice: 161,
    premiumPrice: 242,
    minOrder: 100,
    maxOrder: 25000,
    deliveryTime: "2–8 hours",
    refill: true,
    rating: 5,
    description: "UAE geo-targeted followers for Gulf market growth.",
    speed: "fast",
    successRate: 96,
    retentionScore: 89,
    refillPolicy: "guaranteed",
    urgencySignal: "🇦🇪 UAE Targeted",
  },
  {
    id: "ig-usa-followers",
    name: "Instagram USA Followers",
    category: "instagram",
    pricePerThousand: 149,
    basicPrice: 149,
    recommendedPrice: 186,
    premiumPrice: 279,
    minOrder: 100,
    maxOrder: 25000,
    deliveryTime: "2–8 hours",
    refill: true,
    rating: 5,
    description: "USA geo-targeted followers for American market.",
    speed: "fast",
    successRate: 95,
    retentionScore: 88,
    refillPolicy: "guaranteed",
    urgencySignal: "🇺🇸 USA Targeted",
  },
  {
    id: "ig-reels-views",
    name: "Instagram Reels Views",
    category: "instagram",
    pricePerThousand: 15,
    basicPrice: 15,
    recommendedPrice: 19,
    premiumPrice: 28,
    minOrder: 1000,
    maxOrder: 10000000,
    deliveryTime: "1–3 hours",
    refill: false,
    rating: 4,
    description: "Boost Reels visibility in Explore feed.",
    speed: "fast",
    successRate: 99,
    retentionScore: 80,
    refillPolicy: "none",
    urgencySignal: "⚡ Instant Boost",
  },
  {
    id: "ig-reels-likes",
    name: "Instagram Reels Likes",
    category: "instagram",
    pricePerThousand: 29,
    basicPrice: 29,
    recommendedPrice: 36,
    premiumPrice: 54,
    minOrder: 50,
    maxOrder: 50000,
    deliveryTime: "0–1 hour",
    refill: false,
    rating: 4,
    description: "Real-looking likes on Reels for social proof.",
    speed: "fast",
    successRate: 98,
    retentionScore: 78,
    refillPolicy: "none",
    urgencySignal: "⚡ Fast Delivery",
  },
  {
    id: "ig-story-views",
    name: "Instagram Story Views",
    category: "instagram",
    pricePerThousand: 9,
    basicPrice: 9,
    recommendedPrice: 11,
    premiumPrice: 17,
    minOrder: 500,
    maxOrder: 5000000,
    deliveryTime: "0–30 minutes",
    refill: false,
    rating: 4,
    description: "Instant story views to increase story reach.",
    speed: "fast",
    successRate: 99,
    retentionScore: 75,
    refillPolicy: "none",
    urgencySignal: "⚡ Instant",
  },
  {
    id: "ig-saves",
    name: "Instagram Post Saves",
    category: "instagram",
    pricePerThousand: 39,
    basicPrice: 39,
    recommendedPrice: 49,
    premiumPrice: 73,
    minOrder: 100,
    maxOrder: 20000,
    deliveryTime: "1–6 hours",
    refill: false,
    rating: 4,
    description: "Post saves signal high-value content to the algorithm.",
    speed: "medium",
    successRate: 97,
    retentionScore: 82,
    refillPolicy: "none",
    urgencySignal: "📌 Algorithm Boost",
  },
  {
    id: "ig-shares",
    name: "Instagram Post Shares",
    category: "instagram",
    pricePerThousand: 49,
    basicPrice: 49,
    recommendedPrice: 61,
    premiumPrice: 92,
    minOrder: 100,
    maxOrder: 10000,
    deliveryTime: "2–8 hours",
    refill: false,
    rating: 4,
    description: "Genuine-looking shares to amplify content reach.",
    speed: "medium",
    successRate: 96,
    retentionScore: 80,
    refillPolicy: "none",
    urgencySignal: "📢 Viral Signal",
  },
  {
    id: "ig-custom-comments",
    name: "Instagram Custom Comments",
    category: "instagram",
    pricePerThousand: 199,
    basicPrice: 199,
    recommendedPrice: 249,
    premiumPrice: 373,
    minOrder: 10,
    maxOrder: 5000,
    deliveryTime: "2–12 hours",
    refill: false,
    rating: 5,
    description: "Manually written comments tailored to your post topic.",
    speed: "medium",
    successRate: 97,
    retentionScore: 88,
    refillPolicy: "none",
    urgencySignal: "✍️ Manual Quality",
  },
  {
    id: "ig-profile-visits",
    name: "Instagram Profile Visits",
    category: "instagram",
    pricePerThousand: 19,
    basicPrice: 19,
    recommendedPrice: 24,
    premiumPrice: 36,
    minOrder: 1000,
    maxOrder: 1000000,
    deliveryTime: "1–4 hours",
    refill: false,
    rating: 3,
    description: "Profile visits to boost your visibility score.",
    speed: "fast",
    successRate: 95,
    retentionScore: 70,
    refillPolicy: "none",
    urgencySignal: "👁️ Visibility Boost",
  },
  // ─── YouTube (7) ─────────────────────────────────────────────────────────────
  {
    id: "yt-views",
    name: "YouTube Views",
    category: "youtube",
    pricePerThousand: 18,
    basicPrice: 18,
    recommendedPrice: 23,
    premiumPrice: 34,
    minOrder: 1000,
    maxOrder: 5000000,
    deliveryTime: "2–6 hours",
    refill: false,
    rating: 4,
    description: "AdSense-safe views with avg 2–3 min watch time.",
    speed: "medium",
    successRate: 98,
    retentionScore: 82,
    refillPolicy: "none",
    urgencySignal: "🎬 High Retention",
  },
  {
    id: "yt-shorts-views",
    name: "YouTube Shorts Views",
    category: "youtube",
    pricePerThousand: 12,
    basicPrice: 12,
    recommendedPrice: 15,
    premiumPrice: 23,
    minOrder: 1000,
    maxOrder: 10000000,
    deliveryTime: "0–2 hours",
    refill: false,
    rating: 4,
    description: "Fast views for Shorts to trigger algorithm push.",
    speed: "fast",
    successRate: 99,
    retentionScore: 78,
    refillPolicy: "none",
    urgencySignal: "⚡ Shorts Boost",
  },
  {
    id: "yt-subscribers",
    name: "YouTube Subscribers",
    category: "youtube",
    pricePerThousand: 249,
    basicPrice: 249,
    recommendedPrice: 311,
    premiumPrice: 467,
    minOrder: 100,
    maxOrder: 20000,
    deliveryTime: "1–3 days",
    refill: true,
    rating: 5,
    description: "Real-looking subscribers safe for monetization.",
    speed: "medium",
    successRate: 97,
    retentionScore: 91,
    refillPolicy: "guaranteed",
    urgencySignal: "💎 High Quality",
  },
  {
    id: "yt-likes",
    name: "YouTube Video Likes",
    category: "youtube",
    pricePerThousand: 49,
    basicPrice: 49,
    recommendedPrice: 61,
    premiumPrice: 92,
    minOrder: 100,
    maxOrder: 50000,
    deliveryTime: "1–4 hours",
    refill: false,
    rating: 4,
    description: "Genuine-looking video likes to boost engagement.",
    speed: "fast",
    successRate: 98,
    retentionScore: 80,
    refillPolicy: "none",
    urgencySignal: "👍 Engagement Boost",
  },
  {
    id: "yt-comments",
    name: "YouTube Comments",
    category: "youtube",
    pricePerThousand: 299,
    basicPrice: 299,
    recommendedPrice: 374,
    premiumPrice: 561,
    minOrder: 10,
    maxOrder: 2000,
    deliveryTime: "4–24 hours",
    refill: false,
    rating: 5,
    description: "Custom comments relevant to your video topic.",
    speed: "medium",
    successRate: 96,
    retentionScore: 86,
    refillPolicy: "none",
    urgencySignal: "✍️ Custom Written",
  },
  {
    id: "yt-watchtime",
    name: "YouTube Watch Time – 4000h",
    category: "youtube",
    pricePerThousand: 599,
    basicPrice: 599,
    recommendedPrice: 749,
    premiumPrice: 1124,
    minOrder: 500,
    maxOrder: 10000,
    deliveryTime: "7–15 days",
    refill: false,
    rating: 5,
    description: "Complete 4000-hour watch time for monetization.",
    speed: "slow",
    successRate: 99,
    retentionScore: 95,
    refillPolicy: "none",
    urgencySignal: "🏆 Monetization Pack",
  },
  {
    id: "yt-livestream-views",
    name: "YouTube Live Stream Views",
    category: "youtube",
    pricePerThousand: 89,
    basicPrice: 89,
    recommendedPrice: 111,
    premiumPrice: 167,
    minOrder: 100,
    maxOrder: 20000,
    deliveryTime: "0–15 minutes",
    refill: false,
    rating: 4,
    description: "Instant live stream viewers to boost ranking.",
    speed: "fast",
    successRate: 97,
    retentionScore: 83,
    refillPolicy: "none",
    urgencySignal: "🔴 Live Boost",
  },
  // ─── Facebook (6) ────────────────────────────────────────────────────────────
  {
    id: "fb-page-likes",
    name: "Facebook Page Likes",
    category: "facebook",
    pricePerThousand: 119,
    basicPrice: 119,
    recommendedPrice: 149,
    premiumPrice: 223,
    minOrder: 100,
    maxOrder: 25000,
    deliveryTime: "12–48 hours",
    refill: true,
    rating: 4,
    description: "Targeted page likes for Facebook business pages.",
    speed: "medium",
    successRate: 96,
    retentionScore: 85,
    refillPolicy: "limited",
    urgencySignal: "👥 Social Proof",
  },
  {
    id: "fb-post-likes",
    name: "Facebook Post Likes",
    category: "facebook",
    pricePerThousand: 39,
    basicPrice: 39,
    recommendedPrice: 49,
    premiumPrice: 73,
    minOrder: 50,
    maxOrder: 20000,
    deliveryTime: "0–2 hours",
    refill: false,
    rating: 4,
    description: "Instant post likes for Facebook content.",
    speed: "fast",
    successRate: 97,
    retentionScore: 78,
    refillPolicy: "none",
    urgencySignal: "⚡ Fast Delivery",
  },
  {
    id: "fb-video-views",
    name: "Facebook Video Views",
    category: "facebook",
    pricePerThousand: 19,
    basicPrice: 19,
    recommendedPrice: 24,
    premiumPrice: 36,
    minOrder: 1000,
    maxOrder: 5000000,
    deliveryTime: "1–4 hours",
    refill: false,
    rating: 4,
    description: "Real-looking video views for Facebook videos.",
    speed: "fast",
    successRate: 98,
    retentionScore: 76,
    refillPolicy: "none",
    urgencySignal: "📺 Video Boost",
  },
  {
    id: "fb-group-members",
    name: "Facebook Group Members",
    category: "facebook",
    pricePerThousand: 149,
    basicPrice: 149,
    recommendedPrice: 186,
    premiumPrice: 279,
    minOrder: 100,
    maxOrder: 10000,
    deliveryTime: "1–3 days",
    refill: false,
    rating: 4,
    description: "Grow your Facebook group with real-looking members.",
    speed: "medium",
    successRate: 94,
    retentionScore: 82,
    refillPolicy: "none",
    urgencySignal: "👥 Community Growth",
  },
  {
    id: "fb-comments",
    name: "Facebook Comments",
    category: "facebook",
    pricePerThousand: 249,
    basicPrice: 249,
    recommendedPrice: 311,
    premiumPrice: 467,
    minOrder: 10,
    maxOrder: 2000,
    deliveryTime: "4–24 hours",
    refill: false,
    rating: 4,
    description: "Custom comments to boost post engagement.",
    speed: "medium",
    successRate: 95,
    retentionScore: 80,
    refillPolicy: "none",
    urgencySignal: "✍️ Custom Comments",
  },
  {
    id: "fb-shares",
    name: "Facebook Post Shares",
    category: "facebook",
    pricePerThousand: 59,
    basicPrice: 59,
    recommendedPrice: 74,
    premiumPrice: 111,
    minOrder: 50,
    maxOrder: 5000,
    deliveryTime: "2–8 hours",
    refill: false,
    rating: 3,
    description: "Shares to amplify your Facebook post reach.",
    speed: "medium",
    successRate: 93,
    retentionScore: 74,
    refillPolicy: "none",
    urgencySignal: "📢 Reach Boost",
  },
  // ─── TikTok (5) ──────────────────────────────────────────────────────────────
  {
    id: "tt-followers",
    name: "TikTok Followers",
    category: "tiktok",
    pricePerThousand: 69,
    basicPrice: 69,
    recommendedPrice: 86,
    premiumPrice: 129,
    minOrder: 100,
    maxOrder: 50000,
    deliveryTime: "0–6 hours",
    refill: true,
    rating: 4,
    description: "Real-looking TikTok followers to boost credibility.",
    speed: "fast",
    successRate: 97,
    retentionScore: 86,
    refillPolicy: "limited",
    urgencySignal: "🔥 High Demand",
  },
  {
    id: "tt-likes",
    name: "TikTok Video Likes",
    category: "tiktok",
    pricePerThousand: 19,
    basicPrice: 19,
    recommendedPrice: 24,
    premiumPrice: 36,
    minOrder: 100,
    maxOrder: 100000,
    deliveryTime: "0–1 hour",
    refill: false,
    rating: 4,
    description: "Instant likes to push videos to the For You page.",
    speed: "fast",
    successRate: 99,
    retentionScore: 78,
    refillPolicy: "none",
    urgencySignal: "⚡ FYP Boost",
  },
  {
    id: "tt-views",
    name: "TikTok Video Views",
    category: "tiktok",
    pricePerThousand: 9,
    basicPrice: 9,
    recommendedPrice: 11,
    premiumPrice: 17,
    minOrder: 1000,
    maxOrder: 100000000,
    deliveryTime: "0–30 minutes",
    refill: false,
    rating: 4,
    description: "Viral pack views for TikTok algorithm boost.",
    speed: "fast",
    successRate: 99,
    retentionScore: 75,
    refillPolicy: "none",
    urgencySignal: "🚀 Viral Pack",
  },
  {
    id: "tt-shares",
    name: "TikTok Video Shares",
    category: "tiktok",
    pricePerThousand: 49,
    basicPrice: 49,
    recommendedPrice: 61,
    premiumPrice: 92,
    minOrder: 100,
    maxOrder: 10000,
    deliveryTime: "2–8 hours",
    refill: false,
    rating: 4,
    description: "Shares to amplify TikTok content reach.",
    speed: "medium",
    successRate: 96,
    retentionScore: 79,
    refillPolicy: "none",
    urgencySignal: "📢 Share Boost",
  },
  {
    id: "tt-comments",
    name: "TikTok Comments",
    category: "tiktok",
    pricePerThousand: 229,
    basicPrice: 229,
    recommendedPrice: 286,
    premiumPrice: 429,
    minOrder: 10,
    maxOrder: 2000,
    deliveryTime: "4–12 hours",
    refill: false,
    rating: 4,
    description: "Custom comments for TikTok engagement.",
    speed: "medium",
    successRate: 95,
    retentionScore: 82,
    refillPolicy: "none",
    urgencySignal: "✍️ Custom",
  },
  // ─── Telegram (4) ────────────────────────────────────────────────────────────
  {
    id: "tg-channel-members",
    name: "Telegram Channel Members",
    category: "telegram",
    pricePerThousand: 79,
    basicPrice: 79,
    recommendedPrice: 99,
    premiumPrice: 148,
    minOrder: 100,
    maxOrder: 200000,
    deliveryTime: "1–12 hours",
    refill: false,
    rating: 4,
    description: "Real-looking members for Telegram channels.",
    speed: "medium",
    successRate: 97,
    retentionScore: 84,
    refillPolicy: "none",
    urgencySignal: "📡 Non-Drop",
  },
  {
    id: "tg-post-views",
    name: "Telegram Post Views",
    category: "telegram",
    pricePerThousand: 5,
    basicPrice: 5,
    recommendedPrice: 6,
    premiumPrice: 9,
    minOrder: 500,
    maxOrder: 1000000,
    deliveryTime: "0–15 minutes",
    refill: false,
    rating: 4,
    description: "Instant post views to make channel look active.",
    speed: "fast",
    successRate: 99,
    retentionScore: 72,
    refillPolicy: "none",
    urgencySignal: "⚡ Instant",
  },
  {
    id: "tg-reactions",
    name: "Telegram Post Reactions",
    category: "telegram",
    pricePerThousand: 19,
    basicPrice: 19,
    recommendedPrice: 24,
    premiumPrice: 36,
    minOrder: 100,
    maxOrder: 50000,
    deliveryTime: "0–30 minutes",
    refill: false,
    rating: 4,
    description: "Emoji reactions for Telegram posts.",
    speed: "fast",
    successRate: 99,
    retentionScore: 74,
    refillPolicy: "none",
    urgencySignal: "👍 Engagement",
  },
  {
    id: "tg-group-members",
    name: "Telegram Group Members",
    category: "telegram",
    pricePerThousand: 89,
    basicPrice: 89,
    recommendedPrice: 111,
    premiumPrice: 167,
    minOrder: 100,
    maxOrder: 100000,
    deliveryTime: "2–12 hours",
    refill: false,
    rating: 4,
    description: "Real-looking members for Telegram groups.",
    speed: "medium",
    successRate: 96,
    retentionScore: 82,
    refillPolicy: "none",
    urgencySignal: "👥 Group Growth",
  },
  // ─── Website Traffic (6) ─────────────────────────────────────────────────────
  {
    id: "web-india-traffic",
    name: "Website Traffic – India",
    category: "website",
    pricePerThousand: 29,
    basicPrice: 29,
    recommendedPrice: 36,
    premiumPrice: 54,
    minOrder: 1000,
    maxOrder: 1000000,
    deliveryTime: "1–24 hours",
    refill: false,
    rating: 4,
    description: "India geo-targeted real-looking traffic.",
    speed: "medium",
    successRate: 98,
    retentionScore: 80,
    refillPolicy: "none",
    urgencySignal: "🇮🇳 India Traffic",
  },
  {
    id: "web-uae-traffic",
    name: "Website Traffic – UAE",
    category: "website",
    pricePerThousand: 49,
    basicPrice: 49,
    recommendedPrice: 61,
    premiumPrice: 92,
    minOrder: 1000,
    maxOrder: 500000,
    deliveryTime: "2–24 hours",
    refill: false,
    rating: 4,
    description: "UAE geo-targeted real-looking traffic.",
    speed: "medium",
    successRate: 97,
    retentionScore: 78,
    refillPolicy: "none",
    urgencySignal: "🇦🇪 UAE Traffic",
  },
  {
    id: "web-usa-traffic",
    name: "Website Traffic – USA",
    category: "website",
    pricePerThousand: 59,
    basicPrice: 59,
    recommendedPrice: 74,
    premiumPrice: 111,
    minOrder: 1000,
    maxOrder: 500000,
    deliveryTime: "2–24 hours",
    refill: false,
    rating: 4,
    description: "USA geo-targeted real-looking traffic.",
    speed: "medium",
    successRate: 97,
    retentionScore: 79,
    refillPolicy: "none",
    urgencySignal: "🇺🇸 USA Traffic",
  },
  {
    id: "web-seo-traffic",
    name: "SEO Organic Traffic",
    category: "website",
    pricePerThousand: 79,
    basicPrice: 79,
    recommendedPrice: 99,
    premiumPrice: 148,
    minOrder: 1000,
    maxOrder: 500000,
    deliveryTime: "3–48 hours",
    refill: false,
    rating: 5,
    description: "Search-engine referral traffic that looks organic.",
    speed: "medium",
    successRate: 96,
    retentionScore: 85,
    refillPolicy: "none",
    urgencySignal: "🔍 SEO Safe",
  },
  {
    id: "web-keyword-traffic",
    name: "Keyword Targeted Traffic",
    category: "website",
    pricePerThousand: 99,
    basicPrice: 99,
    recommendedPrice: 124,
    premiumPrice: 186,
    minOrder: 500,
    maxOrder: 200000,
    deliveryTime: "4–48 hours",
    refill: false,
    rating: 5,
    description: "Traffic arriving via specific search keywords.",
    speed: "medium",
    successRate: 95,
    retentionScore: 87,
    refillPolicy: "none",
    urgencySignal: "🎯 Keyword Match",
  },
  {
    id: "web-dwell-traffic",
    name: "High Dwell-Time Traffic",
    category: "website",
    pricePerThousand: 119,
    basicPrice: 119,
    recommendedPrice: 149,
    premiumPrice: 223,
    minOrder: 500,
    maxOrder: 200000,
    deliveryTime: "6–48 hours",
    refill: false,
    rating: 5,
    description: "Long-session visitors that reduce bounce rate.",
    speed: "slow",
    successRate: 94,
    retentionScore: 90,
    refillPolicy: "none",
    urgencySignal: "⏱️ Long Sessions",
  },
  // ─── Business Growth (6) ─────────────────────────────────────────────────────
  {
    id: "biz-google-reviews",
    name: "Google Review Service",
    category: "business",
    pricePerThousand: 4999,
    basicPrice: 4999,
    recommendedPrice: 6249,
    premiumPrice: 9374,
    minOrder: 5,
    maxOrder: 500,
    deliveryTime: "2–7 days",
    refill: false,
    rating: 5,
    description: "Verified Google reviews for local business profiles.",
    speed: "slow",
    successRate: 96,
    retentionScore: 92,
    refillPolicy: "none",
    urgencySignal: "⭐ 5-Star Reviews",
  },
  {
    id: "biz-maps-ranking",
    name: "Google Maps Ranking Boost",
    category: "business",
    pricePerThousand: 2999,
    basicPrice: 2999,
    recommendedPrice: 3749,
    premiumPrice: 5624,
    minOrder: 1,
    maxOrder: 100,
    deliveryTime: "7–30 days",
    refill: false,
    rating: 5,
    description: "Boost your Maps local ranking for target keywords.",
    speed: "slow",
    successRate: 88,
    retentionScore: 90,
    refillPolicy: "none",
    urgencySignal: "📍 Local SEO",
  },
  {
    id: "biz-website-campaign",
    name: "Website Visitor Campaign",
    category: "business",
    pricePerThousand: 199,
    basicPrice: 199,
    recommendedPrice: 249,
    premiumPrice: 374,
    minOrder: 100,
    maxOrder: 100000,
    deliveryTime: "1–7 days",
    refill: false,
    rating: 4,
    description: "Targeted visitor campaigns for business websites.",
    speed: "medium",
    successRate: 93,
    retentionScore: 84,
    refillPolicy: "none",
    urgencySignal: "🌐 Business Traffic",
  },
  {
    id: "biz-local-promo",
    name: "Local Business Promotion",
    category: "business",
    pricePerThousand: 1499,
    basicPrice: 1499,
    recommendedPrice: 1874,
    premiumPrice: 2811,
    minOrder: 1,
    maxOrder: 500,
    deliveryTime: "3–14 days",
    refill: false,
    rating: 4,
    description: "Multi-channel promotion for local businesses.",
    speed: "slow",
    successRate: 91,
    retentionScore: 86,
    refillPolicy: "none",
    urgencySignal: "🏪 Local Growth",
  },
  {
    id: "biz-whatsapp-leads",
    name: "WhatsApp Lead Campaign",
    category: "business",
    pricePerThousand: 2499,
    basicPrice: 2499,
    recommendedPrice: 3124,
    premiumPrice: 4686,
    minOrder: 10,
    maxOrder: 1000,
    deliveryTime: "2–10 days",
    refill: false,
    rating: 4,
    description: "Qualified leads via WhatsApp message campaigns.",
    speed: "medium",
    successRate: 89,
    retentionScore: 88,
    refillPolicy: "none",
    urgencySignal: "💬 Lead Generation",
  },
  {
    id: "biz-influencer-shoutout",
    name: "Influencer Shoutout Booking",
    category: "business",
    pricePerThousand: 4999,
    basicPrice: 4999,
    recommendedPrice: 6249,
    premiumPrice: 9374,
    minOrder: 1,
    maxOrder: 50,
    deliveryTime: "1–5 days",
    refill: false,
    rating: 5,
    description: "Authentic shoutouts from verified influencers.",
    speed: "medium",
    successRate: 94,
    retentionScore: 91,
    refillPolicy: "none",
    urgencySignal: "📢 Influencer Reach",
  },
  // ─── AI Growth Tools (6) ─────────────────────────────────────────────────────
  {
    id: "ai-caption-gen",
    name: "Caption Generator",
    category: "ai",
    pricePerThousand: 99,
    basicPrice: 99,
    recommendedPrice: 124,
    premiumPrice: 186,
    minOrder: 10,
    maxOrder: 1000,
    deliveryTime: "Instant",
    refill: false,
    rating: 5,
    description: "AI-powered captions optimized for engagement and reach.",
    speed: "fast",
    successRate: 98,
    retentionScore: 88,
    refillPolicy: "none",
    urgencySignal: "🤖 AI Powered",
  },
  {
    id: "ai-hashtag-gen",
    name: "Hashtag Generator",
    category: "ai",
    pricePerThousand: 79,
    basicPrice: 79,
    recommendedPrice: 99,
    premiumPrice: 148,
    minOrder: 10,
    maxOrder: 1000,
    deliveryTime: "Instant",
    refill: false,
    rating: 5,
    description: "Trending hashtag sets tailored to your niche.",
    speed: "fast",
    successRate: 97,
    retentionScore: 85,
    refillPolicy: "none",
    urgencySignal: "📊 Trending Tags",
  },
  {
    id: "ai-bio-optimizer",
    name: "Bio Optimizer",
    category: "ai",
    pricePerThousand: 149,
    basicPrice: 149,
    recommendedPrice: 186,
    premiumPrice: 279,
    minOrder: 1,
    maxOrder: 100,
    deliveryTime: "Instant",
    refill: false,
    rating: 5,
    description: "Conversion-focused bio rewrite for your profile.",
    speed: "fast",
    successRate: 97,
    retentionScore: 87,
    refillPolicy: "none",
    urgencySignal: "✨ Profile Boost",
  },
  {
    id: "ai-viral-hook",
    name: "Viral Hook Generator",
    category: "ai",
    pricePerThousand: 129,
    basicPrice: 129,
    recommendedPrice: 161,
    premiumPrice: 242,
    minOrder: 10,
    maxOrder: 500,
    deliveryTime: "Instant",
    refill: false,
    rating: 5,
    description: "High-CTR opening hooks for posts and Reels.",
    speed: "fast",
    successRate: 96,
    retentionScore: 86,
    refillPolicy: "none",
    urgencySignal: "🎣 Viral Hooks",
  },
  {
    id: "ai-content-calendar",
    name: "Content Calendar Generator",
    category: "ai",
    pricePerThousand: 199,
    basicPrice: 199,
    recommendedPrice: 249,
    premiumPrice: 374,
    minOrder: 1,
    maxOrder: 100,
    deliveryTime: "Instant",
    refill: false,
    rating: 5,
    description: "30-day content schedule tailored to your brand.",
    speed: "fast",
    successRate: 95,
    retentionScore: 90,
    refillPolicy: "none",
    urgencySignal: "📅 30-Day Plan",
  },
  {
    id: "ai-competitor-analyzer",
    name: "Competitor Profile Analyzer",
    category: "ai",
    pricePerThousand: 249,
    basicPrice: 249,
    recommendedPrice: 311,
    premiumPrice: 467,
    minOrder: 1,
    maxOrder: 50,
    deliveryTime: "Instant",
    refill: false,
    rating: 5,
    description: "Deep analysis of competitor profiles and strategies.",
    speed: "fast",
    successRate: 94,
    retentionScore: 89,
    refillPolicy: "none",
    urgencySignal: "🔬 Competitor Intel",
  },
];

export type SortOption = "cheapest" | "fastest" | "best_quality";

const SPEED_ORDER: Record<Service["speed"], number> = {
  fast: 0,
  medium: 1,
  slow: 2,
};

interface UseServicesOptions {
  platform: ServiceCategory | "all";
  sort: SortOption;
  search: string;
}

export function useServices({ platform, sort, search }: UseServicesOptions) {
  const filtered = useMemo(() => {
    let list = MOCK_SERVICES;

    if (platform !== "all") {
      list = list.filter((s) => s.category === platform);
    }

    if (search.trim()) {
      const q = search.trim().toLowerCase();
      list = list.filter(
        (s) =>
          s.name.toLowerCase().includes(q) ||
          s.description.toLowerCase().includes(q),
      );
    }

    if (sort === "cheapest") {
      list = [...list].sort((a, b) => a.pricePerThousand - b.pricePerThousand);
    } else if (sort === "fastest") {
      list = [...list].sort(
        (a, b) => SPEED_ORDER[a.speed] - SPEED_ORDER[b.speed],
      );
    } else if (sort === "best_quality") {
      list = [...list].sort((a, b) => b.rating - a.rating);
    }

    return list;
  }, [platform, sort, search]);

  return filtered;
}
