/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceId = IDL.Nat;
export const BundleService = IDL.Record({
  'quantity' : IDL.Nat,
  'serviceId' : ServiceId,
});
export const BundlePublic = IDL.Record({
  'id' : IDL.Nat,
  'hasPremiumUpgrade' : IDL.Bool,
  'originalPrice' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'estimatedDeliveryHours' : IDL.Nat,
  'isActive' : IDL.Bool,
  'imageEmoji' : IDL.Text,
  'badge' : IDL.Text,
  'discountedPrice' : IDL.Nat,
  'services' : IDL.Vec(BundleService),
});
export const Timestamp = IDL.Int;
export const CouponPublic = IDL.Record({
  'id' : IDL.Nat,
  'expiryDate' : Timestamp,
  'code' : IDL.Text,
  'maxUsageCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'usageCount' : IDL.Nat,
  'applicableServices' : IDL.Vec(ServiceId),
  'isActive' : IDL.Bool,
  'discountPercentage' : IDL.Float64,
});
export const CurrencyPublic = IDL.Record({
  'displayName' : IDL.Text,
  'code' : IDL.Text,
  'flag' : IDL.Text,
  'isActive' : IDL.Bool,
  'exchangeRate' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserId = IDL.Principal;
export const TransactionId = IDL.Nat;
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
  'refund' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const AdminPricingRulePublic = IDL.Record({
  'id' : IDL.Nat,
  'recommendedMargin' : IDL.Float64,
  'createdAt' : Timestamp,
  'basicMargin' : IDL.Float64,
  'isActive' : IDL.Bool,
  'currencyOverrides' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'premiumMargin' : IDL.Float64,
  'targetServices' : IDL.Vec(ServiceId),
});
export const ProviderStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
  'testing' : IDL.Null,
});
export const ProviderPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProviderStatus,
  'apiKeyMasked' : IDL.Text,
  'successRate' : IDL.Float64,
  'name' : IDL.Text,
  'avgResponseMs' : IDL.Nat,
  'apiUrl' : IDL.Text,
  'commissionPercent' : IDL.Float64,
  'priority' : IDL.Nat,
  'failedLast24h' : IDL.Nat,
});
export const Platform = IDL.Variant({
  'ai' : IDL.Null,
  'tiktok' : IDL.Null,
  'twitter' : IDL.Null,
  'instagram' : IDL.Null,
  'website' : IDL.Null,
  'facebook' : IDL.Null,
  'business' : IDL.Null,
  'youtube' : IDL.Null,
  'telegram' : IDL.Null,
});
export const RefillPolicy = IDL.Variant({
  'none' : IDL.Null,
  'guaranteed' : IDL.Null,
  'limited' : IDL.Null,
});
export const ServicePublic = IDL.Record({
  'id' : ServiceId,
  'currencyPrices' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'pricePerThousand' : IDL.Nat,
  'reliabilityScore' : IDL.Nat,
  'refillPolicy' : RefillPolicy,
  'maxQuantity' : IDL.Nat,
  'urgencySignal' : IDL.Text,
  'basicPrice' : IDL.Nat,
  'premiumPrice' : IDL.Nat,
  'hasRefill' : IDL.Bool,
  'successRate' : IDL.Nat,
  'name' : IDL.Text,
  'deliveryTimeHours' : IDL.Nat,
  'platform' : Platform,
  'isActive' : IDL.Bool,
  'recommendedPrice' : IDL.Nat,
  'retentionScore' : IDL.Nat,
  'category' : IDL.Text,
  'qualityRating' : IDL.Nat,
  'providerId' : IDL.Opt(IDL.Nat),
  'minQuantity' : IDL.Nat,
  'baseCost' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const OrderPublic = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'userId' : UserId,
  'link' : IDL.Text,
  'createdAt' : Timestamp,
  'estimatedDelivery' : Timestamp,
  'quantity' : IDL.Nat,
  'serviceId' : ServiceId,
  'totalPrice' : IDL.Nat,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserPublic = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'avatar' : IDL.Opt(IDL.Text),
});
export const AdminConfig = IDL.Record({
  'referralsEnabled' : IDL.Bool,
  'globalMarginPercent' : IDL.Float64,
  'maxOrdersPerUserPerDay' : IDL.Nat,
  'autoRefundHours' : IDL.Nat,
  'fraudDuplicateLinkThreshold' : IDL.Nat,
  'subscriptionsEnabled' : IDL.Bool,
  'fraudVelocityLimit' : IDL.Nat,
  'minUserAgeDays' : IDL.Nat,
  'maxConcurrentOrdersPerLink' : IDL.Nat,
});
export const TopServiceStat = IDL.Record({
  'revenue' : IDL.Float64,
  'name' : IDL.Text,
  'serviceId' : IDL.Nat,
  'unitsSold' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'subscriptionRevenue' : IDL.Record({
    'pro' : IDL.Nat,
    'premium' : IDL.Nat,
    'free' : IDL.Nat,
  }),
  'dailyRevenue' : IDL.Vec(IDL.Float64),
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
  'topServices' : IDL.Vec(TopServiceStat),
  'totalActiveOrders' : IDL.Nat,
  'profitMarginPercent' : IDL.Float64,
  'newUsersThisMonth' : IDL.Nat,
  'avgOrderValue' : IDL.Float64,
  'dailyOrders' : IDL.Vec(IDL.Nat),
});
export const AlertType = IDL.Variant({
  'bulkOrders' : IDL.Null,
  'lowServiceRatio' : IDL.Null,
  'highVelocity' : IDL.Null,
  'duplicateLink' : IDL.Null,
});
export const AlertAction = IDL.Variant({
  'blocked' : IDL.Null,
  'whitelisted' : IDL.Null,
  'flagged' : IDL.Null,
});
export const FraudAlertPublic = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'alertType' : AlertType,
  'userId' : IDL.Text,
  'orderId' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'actionTaken' : AlertAction,
  'riskScore' : IDL.Nat,
});
export const LogStatus = IDL.Variant({
  'error' : IDL.Null,
  'success' : IDL.Null,
});
export const SystemLog = IDL.Record({
  'id' : IDL.Nat,
  'status' : LogStatus,
  'action' : IDL.Text,
  'actorId' : IDL.Text,
  'timestamp' : IDL.Int,
  'targetType' : IDL.Text,
  'details' : IDL.Text,
  'targetId' : IDL.Text,
});
export const ServiceStat = IDL.Record({
  'name' : IDL.Text,
  'serviceId' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
  'unitsSold' : IDL.Nat,
  'profitMarginPercent' : IDL.Float64,
});
export const RewardType = IDL.Variant({
  'referral' : IDL.Null,
  'spinWheel' : IDL.Null,
  'firstOrder' : IDL.Null,
  'daily' : IDL.Null,
  'cashback' : IDL.Null,
});
export const WalletRewardPublic = IDL.Record({
  'id' : IDL.Nat,
  'percentageAmount' : IDL.Float64,
  'isActive' : IDL.Bool,
  'rewardType' : RewardType,
  'frequency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const TicketId = IDL.Nat;
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'in_progress' : IDL.Null,
  'open' : IDL.Null,
});
export const TicketCategory = IDL.Variant({
  'order' : IDL.Null,
  'billing' : IDL.Null,
  'technical' : IDL.Null,
  'general' : IDL.Null,
});
export const TicketPublic = IDL.Record({
  'id' : TicketId,
  'status' : TicketStatus,
  'subject' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'lastUpdatedAt' : Timestamp,
  'category' : TicketCategory,
});
export const TicketMessageId = IDL.Nat;
export const TicketMessage = IDL.Record({
  'id' : TicketMessageId,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'ticketId' : TicketId,
  'message' : IDL.Text,
  'isAdminReply' : IDL.Bool,
});
export const ReferralStatus = IDL.Variant({
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const ReferralPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReferralStatus,
  'referredUserId' : UserId,
  'createdAt' : Timestamp,
  'earnings' : IDL.Nat,
  'referrerId' : UserId,
  'commissionPercent' : IDL.Float64,
});
export const ApiKeyId = IDL.Nat;
export const ApiKeyPublic = IDL.Record({
  'id' : ApiKeyId,
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'usageCount' : IDL.Nat,
  'maskedKey' : IDL.Text,
  'isActive' : IDL.Bool,
  'lastUsed' : IDL.Opt(Timestamp),
});
export const ReviewPublic = IDL.Record({
  'id' : IDL.Nat,
  'displayOrder' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'serviceId' : ServiceId,
  'adminApproved' : IDL.Bool,
});
export const ActivityType = IDL.Variant({
  'referralEarn' : IDL.Null,
  'spinWheel' : IDL.Null,
  'firstOrder' : IDL.Null,
  'dailyLogin' : IDL.Null,
  'coupon' : IDL.Null,
  'cashback' : IDL.Null,
});
export const EngagementLog = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : ActivityType,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
});
export const LevelName = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
});
export const UserLevelPublic = IDL.Record({
  'id' : IDL.Nat,
  'maxSpend' : IDL.Nat,
  'displayName' : IDL.Text,
  'cashbackPercent' : IDL.Float64,
  'minSpend' : IDL.Nat,
  'levelName' : LevelName,
  'badge' : IDL.Text,
  'perks' : IDL.Vec(IDL.Text),
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'wallet_alert' : IDL.Null,
  'support_reply' : IDL.Null,
  'order_update' : IDL.Null,
  'promo' : IDL.Null,
});
export const NotificationPublic = IDL.Record({
  'id' : NotificationId,
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const UserStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalSpend' : IDL.Nat,
  'completedOrders' : IDL.Nat,
  'activeOrders' : IDL.Nat,
});
export const SubscriptionPlanId = IDL.Nat;
export const UserSubscriptionPublic = IDL.Record({
  'endDate' : Timestamp,
  'planId' : SubscriptionPlanId,
  'userId' : UserId,
  'isActive' : IDL.Bool,
  'autoRenew' : IDL.Bool,
  'startDate' : Timestamp,
});
export const ServiceSort = IDL.Variant({
  'best' : IDL.Null,
  'cheapest' : IDL.Null,
  'fastest' : IDL.Null,
});
export const PlanTier = IDL.Variant({
  'pro' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const SubscriptionPlan = IDL.Record({
  'id' : SubscriptionPlanId,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'tier' : PlanTier,
  'discountPercent' : IDL.Nat,
  'priceMonthly' : IDL.Nat,
});
export const TicketWithMessages = IDL.Record({
  'ticket' : IDL.Record({
    'id' : TicketId,
    'status' : TicketStatus,
    'subject' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'lastUpdatedAt' : Timestamp,
    'category' : TicketCategory,
  }),
  'messages' : IDL.Vec(TicketMessage),
});
export const TierName = IDL.Variant({
  'premium' : IDL.Null,
  'recommended' : IDL.Null,
  'basic' : IDL.Null,
});
export const SupportLevel = IDL.Variant({
  'dedicated' : IDL.Null,
  'priority' : IDL.Null,
  'standard' : IDL.Null,
});
export const ServiceTierPublic = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'displayName' : IDL.Text,
  'name' : TierName,
  'marginMultiplier' : IDL.Float64,
  'description' : IDL.Text,
  'deliveryMultiplier' : IDL.Float64,
  'isActive' : IDL.Bool,
  'priorityProcessing' : IDL.Bool,
  'refillGuarantee' : IDL.Bool,
  'supportLevel' : SupportLevel,
  'badge' : IDL.Text,
});
export const PlaceOrderRequest = IDL.Record({
  'link' : IDL.Text,
  'quantity' : IDL.Nat,
  'serviceId' : ServiceId,
});

export const idlService = IDL.Service({
  'adminAddBundle' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(BundleService),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
      ],
      [BundlePublic],
      [],
    ),
  'adminAddCoupon' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Nat, Timestamp, IDL.Vec(ServiceId)],
      [CouponPublic],
      [],
    ),
  'adminAddCurrency' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [CurrencyPublic],
      [],
    ),
  'adminAddFunds' : IDL.Func([UserId, IDL.Nat, IDL.Text], [Transaction], []),
  'adminAddPricingRule' : IDL.Func(
      [
        IDL.Vec(ServiceId),
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
      ],
      [AdminPricingRulePublic],
      [],
    ),
  'adminAddProvider' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [ProviderPublic],
      [],
    ),
  'adminAddService' : IDL.Func(
      [
        IDL.Text,
        Platform,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Nat,
        IDL.Nat,
      ],
      [ServicePublic],
      [],
    ),
  'adminAdjustUserWallet' : IDL.Func(
      [IDL.Principal, IDL.Float64, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'adminApproveReview' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'adminBanUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'adminBatchUpdateServicePrices' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Float64],
      [],
      [],
    ),
  'adminCancelOrder' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adminGetAllOrders' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [IDL.Vec(OrderPublic)],
      ['query'],
    ),
  'adminGetAllUsers' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [IDL.Vec(UserPublic)],
      ['query'],
    ),
  'adminGetConfig' : IDL.Func([], [AdminConfig], ['query']),
  'adminGetDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'adminGetFraudAlerts' : IDL.Func(
      [IDL.Opt(IDL.Bool), IDL.Opt(IDL.Nat), IDL.Nat, IDL.Nat],
      [IDL.Vec(FraudAlertPublic)],
      ['query'],
    ),
  'adminGetLogs' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [IDL.Vec(SystemLog)],
      ['query'],
    ),
  'adminGetPricingRules' : IDL.Func(
      [],
      [IDL.Vec(AdminPricingRulePublic)],
      ['query'],
    ),
  'adminGetProviders' : IDL.Func([], [IDL.Vec(ProviderPublic)], ['query']),
  'adminGetServiceStats' : IDL.Func([], [IDL.Vec(ServiceStat)], ['query']),
  'adminGetWalletRewards' : IDL.Func(
      [],
      [IDL.Vec(WalletRewardPublic)],
      ['query'],
    ),
  'adminListOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'adminListTickets' : IDL.Func([], [IDL.Vec(TicketPublic)], ['query']),
  'adminListUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'adminReplyToTicket' : IDL.Func([TicketId, IDL.Text], [TicketMessage], []),
  'adminResolveFraudAlert' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adminSetUserRole' : IDL.Func([UserId, UserRole], [], []),
  'adminUpdateBundle' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Bool)],
      [IDL.Bool],
      [],
    ),
  'adminUpdateConfig' : IDL.Func([AdminConfig], [], []),
  'adminUpdateExchangeRate' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Bool], []),
  'adminUpdateOrderManual' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Nat),
        IDL.Text,
      ],
      [],
      [],
    ),
  'adminUpdateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'adminUpdateProvider' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'adminUpdateService' : IDL.Func(
      [ServiceId, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'adminUpdateServiceVisibility' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'adminUpdateTier' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Bool],
      [],
    ),
  'adminUpdateWalletReward' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Bool)],
      [],
      [],
    ),
  'calculateTierPrice' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'cancelMySubscription' : IDL.Func([], [], []),
  'cancelOrder' : IDL.Func([OrderId], [], []),
  'claimDailyLoginReward' : IDL.Func([], [IDL.Nat], []),
  'closeMyTicket' : IDL.Func([TicketId], [], []),
  'convertPrice' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'createReferral' : IDL.Func([IDL.Principal], [ReferralPublic], []),
  'createTicket' : IDL.Func([IDL.Text, TicketCategory], [TicketPublic], []),
  'generateApiKey' : IDL.Func([IDL.Text], [ApiKeyPublic], []),
  'getAllApprovedReviews' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ReviewPublic)],
      ['query'],
    ),
  'getBundle' : IDL.Func([IDL.Nat], [IDL.Opt(BundlePublic)], ['query']),
  'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyEngagementHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EngagementLog)],
      ['query'],
    ),
  'getMyLevel' : IDL.Func([], [IDL.Opt(UserLevelPublic)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationPublic)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [UserPublic], ['query']),
  'getMyReferrals' : IDL.Func([], [IDL.Vec(ReferralPublic)], ['query']),
  'getMyStats' : IDL.Func([], [UserStats], ['query']),
  'getMySubscription' : IDL.Func(
      [],
      [IDL.Opt(UserSubscriptionPublic)],
      ['query'],
    ),
  'getMyTickets' : IDL.Func([], [IDL.Vec(TicketPublic)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
  'getServicePricing' : IDL.Func(
      [IDL.Nat, ServiceId],
      [IDL.Float64, IDL.Float64, IDL.Float64],
      ['query'],
    ),
  'getServiceReviews' : IDL.Func(
      [ServiceId, IDL.Nat],
      [IDL.Vec(ReviewPublic)],
      ['query'],
    ),
  'getServicesByPlatform' : IDL.Func(
      [Platform],
      [IDL.Vec(ServicePublic)],
      ['query'],
    ),
  'getServicesSorted' : IDL.Func(
      [ServiceSort],
      [IDL.Vec(ServicePublic)],
      ['query'],
    ),
  'getSubscriptionPlans' : IDL.Func([], [IDL.Vec(SubscriptionPlan)], ['query']),
  'getTicketDetail' : IDL.Func(
      [TicketId],
      [IDL.Opt(TicketWithMessages)],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'listBundles' : IDL.Func([], [IDL.Vec(BundlePublic)], ['query']),
  'listCurrencies' : IDL.Func([], [IDL.Vec(CurrencyPublic)], ['query']),
  'listMyApiKeys' : IDL.Func([], [IDL.Vec(ApiKeyPublic)], ['query']),
  'listMyCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
  'listServiceTiers' : IDL.Func([], [IDL.Vec(ServiceTierPublic)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(ServicePublic)], ['query']),
  'listUserLevels' : IDL.Func([], [IDL.Vec(UserLevelPublic)], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [OrderPublic], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserPublic], []),
  'replyToTicket' : IDL.Func([TicketId, IDL.Text], [TicketMessage], []),
  'revokeApiKey' : IDL.Func([ApiKeyId], [], []),
  'searchServices' : IDL.Func([IDL.Text], [IDL.Vec(ServicePublic)], ['query']),
  'spinWheelReward' : IDL.Func([], [IDL.Nat], []),
  'submitReview' : IDL.Func([ServiceId, IDL.Nat, IDL.Text], [ReviewPublic], []),
  'subscribeToPlan' : IDL.Func(
      [SubscriptionPlanId, IDL.Bool],
      [UserSubscriptionPublic],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [UserPublic],
      [],
    ),
  'validateCoupon' : IDL.Func(
      [IDL.Text, ServiceId],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceId = IDL.Nat;
  const BundleService = IDL.Record({
    'quantity' : IDL.Nat,
    'serviceId' : ServiceId,
  });
  const BundlePublic = IDL.Record({
    'id' : IDL.Nat,
    'hasPremiumUpgrade' : IDL.Bool,
    'originalPrice' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'estimatedDeliveryHours' : IDL.Nat,
    'isActive' : IDL.Bool,
    'imageEmoji' : IDL.Text,
    'badge' : IDL.Text,
    'discountedPrice' : IDL.Nat,
    'services' : IDL.Vec(BundleService),
  });
  const Timestamp = IDL.Int;
  const CouponPublic = IDL.Record({
    'id' : IDL.Nat,
    'expiryDate' : Timestamp,
    'code' : IDL.Text,
    'maxUsageCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'usageCount' : IDL.Nat,
    'applicableServices' : IDL.Vec(ServiceId),
    'isActive' : IDL.Bool,
    'discountPercentage' : IDL.Float64,
  });
  const CurrencyPublic = IDL.Record({
    'displayName' : IDL.Text,
    'code' : IDL.Text,
    'flag' : IDL.Text,
    'isActive' : IDL.Bool,
    'exchangeRate' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const TransactionId = IDL.Nat;
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
    'refund' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const AdminPricingRulePublic = IDL.Record({
    'id' : IDL.Nat,
    'recommendedMargin' : IDL.Float64,
    'createdAt' : Timestamp,
    'basicMargin' : IDL.Float64,
    'isActive' : IDL.Bool,
    'currencyOverrides' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'premiumMargin' : IDL.Float64,
    'targetServices' : IDL.Vec(ServiceId),
  });
  const ProviderStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
    'testing' : IDL.Null,
  });
  const ProviderPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProviderStatus,
    'apiKeyMasked' : IDL.Text,
    'successRate' : IDL.Float64,
    'name' : IDL.Text,
    'avgResponseMs' : IDL.Nat,
    'apiUrl' : IDL.Text,
    'commissionPercent' : IDL.Float64,
    'priority' : IDL.Nat,
    'failedLast24h' : IDL.Nat,
  });
  const Platform = IDL.Variant({
    'ai' : IDL.Null,
    'tiktok' : IDL.Null,
    'twitter' : IDL.Null,
    'instagram' : IDL.Null,
    'website' : IDL.Null,
    'facebook' : IDL.Null,
    'business' : IDL.Null,
    'youtube' : IDL.Null,
    'telegram' : IDL.Null,
  });
  const RefillPolicy = IDL.Variant({
    'none' : IDL.Null,
    'guaranteed' : IDL.Null,
    'limited' : IDL.Null,
  });
  const ServicePublic = IDL.Record({
    'id' : ServiceId,
    'currencyPrices' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'pricePerThousand' : IDL.Nat,
    'reliabilityScore' : IDL.Nat,
    'refillPolicy' : RefillPolicy,
    'maxQuantity' : IDL.Nat,
    'urgencySignal' : IDL.Text,
    'basicPrice' : IDL.Nat,
    'premiumPrice' : IDL.Nat,
    'hasRefill' : IDL.Bool,
    'successRate' : IDL.Nat,
    'name' : IDL.Text,
    'deliveryTimeHours' : IDL.Nat,
    'platform' : Platform,
    'isActive' : IDL.Bool,
    'recommendedPrice' : IDL.Nat,
    'retentionScore' : IDL.Nat,
    'category' : IDL.Text,
    'qualityRating' : IDL.Nat,
    'providerId' : IDL.Opt(IDL.Nat),
    'minQuantity' : IDL.Nat,
    'baseCost' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const OrderPublic = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'userId' : UserId,
    'link' : IDL.Text,
    'createdAt' : Timestamp,
    'estimatedDelivery' : Timestamp,
    'quantity' : IDL.Nat,
    'serviceId' : ServiceId,
    'totalPrice' : IDL.Nat,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'avatar' : IDL.Opt(IDL.Text),
  });
  const AdminConfig = IDL.Record({
    'referralsEnabled' : IDL.Bool,
    'globalMarginPercent' : IDL.Float64,
    'maxOrdersPerUserPerDay' : IDL.Nat,
    'autoRefundHours' : IDL.Nat,
    'fraudDuplicateLinkThreshold' : IDL.Nat,
    'subscriptionsEnabled' : IDL.Bool,
    'fraudVelocityLimit' : IDL.Nat,
    'minUserAgeDays' : IDL.Nat,
    'maxConcurrentOrdersPerLink' : IDL.Nat,
  });
  const TopServiceStat = IDL.Record({
    'revenue' : IDL.Float64,
    'name' : IDL.Text,
    'serviceId' : IDL.Nat,
    'unitsSold' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'subscriptionRevenue' : IDL.Record({
      'pro' : IDL.Nat,
      'premium' : IDL.Nat,
      'free' : IDL.Nat,
    }),
    'dailyRevenue' : IDL.Vec(IDL.Float64),
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
    'topServices' : IDL.Vec(TopServiceStat),
    'totalActiveOrders' : IDL.Nat,
    'profitMarginPercent' : IDL.Float64,
    'newUsersThisMonth' : IDL.Nat,
    'avgOrderValue' : IDL.Float64,
    'dailyOrders' : IDL.Vec(IDL.Nat),
  });
  const AlertType = IDL.Variant({
    'bulkOrders' : IDL.Null,
    'lowServiceRatio' : IDL.Null,
    'highVelocity' : IDL.Null,
    'duplicateLink' : IDL.Null,
  });
  const AlertAction = IDL.Variant({
    'blocked' : IDL.Null,
    'whitelisted' : IDL.Null,
    'flagged' : IDL.Null,
  });
  const FraudAlertPublic = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'alertType' : AlertType,
    'userId' : IDL.Text,
    'orderId' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'actionTaken' : AlertAction,
    'riskScore' : IDL.Nat,
  });
  const LogStatus = IDL.Variant({ 'error' : IDL.Null, 'success' : IDL.Null });
  const SystemLog = IDL.Record({
    'id' : IDL.Nat,
    'status' : LogStatus,
    'action' : IDL.Text,
    'actorId' : IDL.Text,
    'timestamp' : IDL.Int,
    'targetType' : IDL.Text,
    'details' : IDL.Text,
    'targetId' : IDL.Text,
  });
  const ServiceStat = IDL.Record({
    'name' : IDL.Text,
    'serviceId' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
    'unitsSold' : IDL.Nat,
    'profitMarginPercent' : IDL.Float64,
  });
  const RewardType = IDL.Variant({
    'referral' : IDL.Null,
    'spinWheel' : IDL.Null,
    'firstOrder' : IDL.Null,
    'daily' : IDL.Null,
    'cashback' : IDL.Null,
  });
  const WalletRewardPublic = IDL.Record({
    'id' : IDL.Nat,
    'percentageAmount' : IDL.Float64,
    'isActive' : IDL.Bool,
    'rewardType' : RewardType,
    'frequency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const TicketId = IDL.Nat;
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'in_progress' : IDL.Null,
    'open' : IDL.Null,
  });
  const TicketCategory = IDL.Variant({
    'order' : IDL.Null,
    'billing' : IDL.Null,
    'technical' : IDL.Null,
    'general' : IDL.Null,
  });
  const TicketPublic = IDL.Record({
    'id' : TicketId,
    'status' : TicketStatus,
    'subject' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'lastUpdatedAt' : Timestamp,
    'category' : TicketCategory,
  });
  const TicketMessageId = IDL.Nat;
  const TicketMessage = IDL.Record({
    'id' : TicketMessageId,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'ticketId' : TicketId,
    'message' : IDL.Text,
    'isAdminReply' : IDL.Bool,
  });
  const ReferralStatus = IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const ReferralPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReferralStatus,
    'referredUserId' : UserId,
    'createdAt' : Timestamp,
    'earnings' : IDL.Nat,
    'referrerId' : UserId,
    'commissionPercent' : IDL.Float64,
  });
  const ApiKeyId = IDL.Nat;
  const ApiKeyPublic = IDL.Record({
    'id' : ApiKeyId,
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'usageCount' : IDL.Nat,
    'maskedKey' : IDL.Text,
    'isActive' : IDL.Bool,
    'lastUsed' : IDL.Opt(Timestamp),
  });
  const ReviewPublic = IDL.Record({
    'id' : IDL.Nat,
    'displayOrder' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'serviceId' : ServiceId,
    'adminApproved' : IDL.Bool,
  });
  const ActivityType = IDL.Variant({
    'referralEarn' : IDL.Null,
    'spinWheel' : IDL.Null,
    'firstOrder' : IDL.Null,
    'dailyLogin' : IDL.Null,
    'coupon' : IDL.Null,
    'cashback' : IDL.Null,
  });
  const EngagementLog = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : ActivityType,
    'userId' : UserId,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
  });
  const LevelName = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
  });
  const UserLevelPublic = IDL.Record({
    'id' : IDL.Nat,
    'maxSpend' : IDL.Nat,
    'displayName' : IDL.Text,
    'cashbackPercent' : IDL.Float64,
    'minSpend' : IDL.Nat,
    'levelName' : LevelName,
    'badge' : IDL.Text,
    'perks' : IDL.Vec(IDL.Text),
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'wallet_alert' : IDL.Null,
    'support_reply' : IDL.Null,
    'order_update' : IDL.Null,
    'promo' : IDL.Null,
  });
  const NotificationPublic = IDL.Record({
    'id' : NotificationId,
    'notifType' : NotificationType,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const UserStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalSpend' : IDL.Nat,
    'completedOrders' : IDL.Nat,
    'activeOrders' : IDL.Nat,
  });
  const SubscriptionPlanId = IDL.Nat;
  const UserSubscriptionPublic = IDL.Record({
    'endDate' : Timestamp,
    'planId' : SubscriptionPlanId,
    'userId' : UserId,
    'isActive' : IDL.Bool,
    'autoRenew' : IDL.Bool,
    'startDate' : Timestamp,
  });
  const ServiceSort = IDL.Variant({
    'best' : IDL.Null,
    'cheapest' : IDL.Null,
    'fastest' : IDL.Null,
  });
  const PlanTier = IDL.Variant({
    'pro' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Record({
    'id' : SubscriptionPlanId,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'tier' : PlanTier,
    'discountPercent' : IDL.Nat,
    'priceMonthly' : IDL.Nat,
  });
  const TicketWithMessages = IDL.Record({
    'ticket' : IDL.Record({
      'id' : TicketId,
      'status' : TicketStatus,
      'subject' : IDL.Text,
      'userId' : UserId,
      'createdAt' : Timestamp,
      'lastUpdatedAt' : Timestamp,
      'category' : TicketCategory,
    }),
    'messages' : IDL.Vec(TicketMessage),
  });
  const TierName = IDL.Variant({
    'premium' : IDL.Null,
    'recommended' : IDL.Null,
    'basic' : IDL.Null,
  });
  const SupportLevel = IDL.Variant({
    'dedicated' : IDL.Null,
    'priority' : IDL.Null,
    'standard' : IDL.Null,
  });
  const ServiceTierPublic = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'displayName' : IDL.Text,
    'name' : TierName,
    'marginMultiplier' : IDL.Float64,
    'description' : IDL.Text,
    'deliveryMultiplier' : IDL.Float64,
    'isActive' : IDL.Bool,
    'priorityProcessing' : IDL.Bool,
    'refillGuarantee' : IDL.Bool,
    'supportLevel' : SupportLevel,
    'badge' : IDL.Text,
  });
  const PlaceOrderRequest = IDL.Record({
    'link' : IDL.Text,
    'quantity' : IDL.Nat,
    'serviceId' : ServiceId,
  });
  
  return IDL.Service({
    'adminAddBundle' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(BundleService),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
        ],
        [BundlePublic],
        [],
      ),
    'adminAddCoupon' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat, Timestamp, IDL.Vec(ServiceId)],
        [CouponPublic],
        [],
      ),
    'adminAddCurrency' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [CurrencyPublic],
        [],
      ),
    'adminAddFunds' : IDL.Func([UserId, IDL.Nat, IDL.Text], [Transaction], []),
    'adminAddPricingRule' : IDL.Func(
        [
          IDL.Vec(ServiceId),
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
        ],
        [AdminPricingRulePublic],
        [],
      ),
    'adminAddProvider' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [ProviderPublic],
        [],
      ),
    'adminAddService' : IDL.Func(
        [
          IDL.Text,
          Platform,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Nat,
          IDL.Nat,
        ],
        [ServicePublic],
        [],
      ),
    'adminAdjustUserWallet' : IDL.Func(
        [IDL.Principal, IDL.Float64, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'adminApproveReview' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'adminBanUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'adminBatchUpdateServicePrices' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Float64],
        [],
        [],
      ),
    'adminCancelOrder' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adminGetAllOrders' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [IDL.Vec(OrderPublic)],
        ['query'],
      ),
    'adminGetAllUsers' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [IDL.Vec(UserPublic)],
        ['query'],
      ),
    'adminGetConfig' : IDL.Func([], [AdminConfig], ['query']),
    'adminGetDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'adminGetFraudAlerts' : IDL.Func(
        [IDL.Opt(IDL.Bool), IDL.Opt(IDL.Nat), IDL.Nat, IDL.Nat],
        [IDL.Vec(FraudAlertPublic)],
        ['query'],
      ),
    'adminGetLogs' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [IDL.Vec(SystemLog)],
        ['query'],
      ),
    'adminGetPricingRules' : IDL.Func(
        [],
        [IDL.Vec(AdminPricingRulePublic)],
        ['query'],
      ),
    'adminGetProviders' : IDL.Func([], [IDL.Vec(ProviderPublic)], ['query']),
    'adminGetServiceStats' : IDL.Func([], [IDL.Vec(ServiceStat)], ['query']),
    'adminGetWalletRewards' : IDL.Func(
        [],
        [IDL.Vec(WalletRewardPublic)],
        ['query'],
      ),
    'adminListOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'adminListTickets' : IDL.Func([], [IDL.Vec(TicketPublic)], ['query']),
    'adminListUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'adminReplyToTicket' : IDL.Func([TicketId, IDL.Text], [TicketMessage], []),
    'adminResolveFraudAlert' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adminSetUserRole' : IDL.Func([UserId, UserRole], [], []),
    'adminUpdateBundle' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Bool)],
        [IDL.Bool],
        [],
      ),
    'adminUpdateConfig' : IDL.Func([AdminConfig], [], []),
    'adminUpdateExchangeRate' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'adminUpdateOrderManual' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Nat),
          IDL.Text,
        ],
        [],
        [],
      ),
    'adminUpdateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'adminUpdateProvider' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'adminUpdateService' : IDL.Func(
        [ServiceId, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'adminUpdateServiceVisibility' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'adminUpdateTier' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Bool],
        [],
      ),
    'adminUpdateWalletReward' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Float64), IDL.Opt(IDL.Bool)],
        [],
        [],
      ),
    'calculateTierPrice' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'cancelMySubscription' : IDL.Func([], [], []),
    'cancelOrder' : IDL.Func([OrderId], [], []),
    'claimDailyLoginReward' : IDL.Func([], [IDL.Nat], []),
    'closeMyTicket' : IDL.Func([TicketId], [], []),
    'convertPrice' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'createReferral' : IDL.Func([IDL.Principal], [ReferralPublic], []),
    'createTicket' : IDL.Func([IDL.Text, TicketCategory], [TicketPublic], []),
    'generateApiKey' : IDL.Func([IDL.Text], [ApiKeyPublic], []),
    'getAllApprovedReviews' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ReviewPublic)],
        ['query'],
      ),
    'getBundle' : IDL.Func([IDL.Nat], [IDL.Opt(BundlePublic)], ['query']),
    'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyEngagementHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EngagementLog)],
        ['query'],
      ),
    'getMyLevel' : IDL.Func([], [IDL.Opt(UserLevelPublic)], ['query']),
    'getMyNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationPublic)],
        ['query'],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [UserPublic], ['query']),
    'getMyReferrals' : IDL.Func([], [IDL.Vec(ReferralPublic)], ['query']),
    'getMyStats' : IDL.Func([], [UserStats], ['query']),
    'getMySubscription' : IDL.Func(
        [],
        [IDL.Opt(UserSubscriptionPublic)],
        ['query'],
      ),
    'getMyTickets' : IDL.Func([], [IDL.Vec(TicketPublic)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
    'getServicePricing' : IDL.Func(
        [IDL.Nat, ServiceId],
        [IDL.Float64, IDL.Float64, IDL.Float64],
        ['query'],
      ),
    'getServiceReviews' : IDL.Func(
        [ServiceId, IDL.Nat],
        [IDL.Vec(ReviewPublic)],
        ['query'],
      ),
    'getServicesByPlatform' : IDL.Func(
        [Platform],
        [IDL.Vec(ServicePublic)],
        ['query'],
      ),
    'getServicesSorted' : IDL.Func(
        [ServiceSort],
        [IDL.Vec(ServicePublic)],
        ['query'],
      ),
    'getSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getTicketDetail' : IDL.Func(
        [TicketId],
        [IDL.Opt(TicketWithMessages)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'listBundles' : IDL.Func([], [IDL.Vec(BundlePublic)], ['query']),
    'listCurrencies' : IDL.Func([], [IDL.Vec(CurrencyPublic)], ['query']),
    'listMyApiKeys' : IDL.Func([], [IDL.Vec(ApiKeyPublic)], ['query']),
    'listMyCoupons' : IDL.Func([], [IDL.Vec(CouponPublic)], ['query']),
    'listServiceTiers' : IDL.Func([], [IDL.Vec(ServiceTierPublic)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(ServicePublic)], ['query']),
    'listUserLevels' : IDL.Func([], [IDL.Vec(UserLevelPublic)], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [OrderPublic], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserPublic], []),
    'replyToTicket' : IDL.Func([TicketId, IDL.Text], [TicketMessage], []),
    'revokeApiKey' : IDL.Func([ApiKeyId], [], []),
    'searchServices' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServicePublic)],
        ['query'],
      ),
    'spinWheelReward' : IDL.Func([], [IDL.Nat], []),
    'submitReview' : IDL.Func(
        [ServiceId, IDL.Nat, IDL.Text],
        [ReviewPublic],
        [],
      ),
    'subscribeToPlan' : IDL.Func(
        [SubscriptionPlanId, IDL.Bool],
        [UserSubscriptionPublic],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [UserPublic],
        [],
      ),
    'validateCoupon' : IDL.Func(
        [IDL.Text, ServiceId],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };