/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityType = { 'referralEarn' : null } |
  { 'spinWheel' : null } |
  { 'firstOrder' : null } |
  { 'dailyLogin' : null } |
  { 'coupon' : null } |
  { 'cashback' : null };
export interface AdminConfig {
  'referralsEnabled' : boolean,
  'globalMarginPercent' : number,
  'maxOrdersPerUserPerDay' : bigint,
  'autoRefundHours' : bigint,
  'fraudDuplicateLinkThreshold' : bigint,
  'subscriptionsEnabled' : boolean,
  'fraudVelocityLimit' : bigint,
  'minUserAgeDays' : bigint,
  'maxConcurrentOrdersPerLink' : bigint,
}
export interface AdminPricingRulePublic {
  'id' : bigint,
  'recommendedMargin' : number,
  'createdAt' : Timestamp,
  'basicMargin' : number,
  'isActive' : boolean,
  'currencyOverrides' : Array<[string, number]>,
  'premiumMargin' : number,
  'targetServices' : Array<ServiceId>,
}
export type AlertAction = { 'blocked' : null } |
  { 'whitelisted' : null } |
  { 'flagged' : null };
export type AlertType = { 'bulkOrders' : null } |
  { 'lowServiceRatio' : null } |
  { 'highVelocity' : null } |
  { 'duplicateLink' : null };
export type ApiKeyId = bigint;
export interface ApiKeyPublic {
  'id' : ApiKeyId,
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'usageCount' : bigint,
  'maskedKey' : string,
  'isActive' : boolean,
  'lastUsed' : [] | [Timestamp],
}
export interface BundlePublic {
  'id' : bigint,
  'hasPremiumUpgrade' : boolean,
  'originalPrice' : bigint,
  'name' : string,
  'description' : string,
  'estimatedDeliveryHours' : bigint,
  'isActive' : boolean,
  'imageEmoji' : string,
  'badge' : string,
  'discountedPrice' : bigint,
  'services' : Array<BundleService>,
}
export interface BundleService { 'quantity' : bigint, 'serviceId' : ServiceId }
export interface CouponPublic {
  'id' : bigint,
  'expiryDate' : Timestamp,
  'code' : string,
  'maxUsageCount' : bigint,
  'createdAt' : Timestamp,
  'usageCount' : bigint,
  'applicableServices' : Array<ServiceId>,
  'isActive' : boolean,
  'discountPercentage' : number,
}
export interface CurrencyPublic {
  'displayName' : string,
  'code' : string,
  'flag' : string,
  'isActive' : boolean,
  'exchangeRate' : number,
  'symbol' : string,
}
export interface DashboardStats {
  'totalOrders' : bigint,
  'subscriptionRevenue' : {
    'pro' : bigint,
    'premium' : bigint,
    'free' : bigint,
  },
  'dailyRevenue' : Array<number>,
  'totalUsers' : bigint,
  'totalRevenue' : number,
  'topServices' : Array<TopServiceStat>,
  'totalActiveOrders' : bigint,
  'profitMarginPercent' : number,
  'newUsersThisMonth' : bigint,
  'avgOrderValue' : number,
  'dailyOrders' : Array<bigint>,
}
export interface EngagementLog {
  'id' : bigint,
  'activityType' : ActivityType,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'amount' : bigint,
}
export interface FraudAlertPublic {
  'id' : bigint,
  'resolved' : boolean,
  'alertType' : AlertType,
  'userId' : string,
  'orderId' : [] | [string],
  'timestamp' : bigint,
  'actionTaken' : AlertAction,
  'riskScore' : bigint,
}
export type LevelName = { 'bronze' : null } |
  { 'gold' : null } |
  { 'platinum' : null } |
  { 'silver' : null };
export type LogStatus = { 'error' : null } |
  { 'success' : null };
export type NotificationId = bigint;
export interface NotificationPublic {
  'id' : NotificationId,
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
}
export type NotificationType = { 'wallet_alert' : null } |
  { 'support_reply' : null } |
  { 'order_update' : null } |
  { 'promo' : null };
export type OrderId = bigint;
export interface OrderPublic {
  'id' : OrderId,
  'status' : OrderStatus,
  'completedAt' : [] | [Timestamp],
  'userId' : UserId,
  'link' : string,
  'createdAt' : Timestamp,
  'estimatedDelivery' : Timestamp,
  'quantity' : bigint,
  'serviceId' : ServiceId,
  'totalPrice' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export interface PlaceOrderRequest {
  'link' : string,
  'quantity' : bigint,
  'serviceId' : ServiceId,
}
export type PlanTier = { 'pro' : null } |
  { 'premium' : null } |
  { 'free' : null };
export type Platform = { 'ai' : null } |
  { 'tiktok' : null } |
  { 'twitter' : null } |
  { 'instagram' : null } |
  { 'website' : null } |
  { 'facebook' : null } |
  { 'business' : null } |
  { 'youtube' : null } |
  { 'telegram' : null };
export interface ProviderPublic {
  'id' : bigint,
  'status' : ProviderStatus,
  'apiKeyMasked' : string,
  'successRate' : number,
  'name' : string,
  'avgResponseMs' : bigint,
  'apiUrl' : string,
  'commissionPercent' : number,
  'priority' : bigint,
  'failedLast24h' : bigint,
}
export type ProviderStatus = { 'active' : null } |
  { 'inactive' : null } |
  { 'testing' : null };
export interface ReferralPublic {
  'id' : bigint,
  'status' : ReferralStatus,
  'referredUserId' : UserId,
  'createdAt' : Timestamp,
  'earnings' : bigint,
  'referrerId' : UserId,
  'commissionPercent' : number,
}
export type ReferralStatus = { 'expired' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type RefillPolicy = { 'none' : null } |
  { 'guaranteed' : null } |
  { 'limited' : null };
export interface ReviewPublic {
  'id' : bigint,
  'displayOrder' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'comment' : string,
  'rating' : bigint,
  'serviceId' : ServiceId,
  'adminApproved' : boolean,
}
export type RewardType = { 'referral' : null } |
  { 'spinWheel' : null } |
  { 'firstOrder' : null } |
  { 'daily' : null } |
  { 'cashback' : null };
export type ServiceId = bigint;
export interface ServicePublic {
  'id' : ServiceId,
  'currencyPrices' : Array<[string, number]>,
  'pricePerThousand' : bigint,
  'reliabilityScore' : bigint,
  'refillPolicy' : RefillPolicy,
  'maxQuantity' : bigint,
  'urgencySignal' : string,
  'basicPrice' : bigint,
  'premiumPrice' : bigint,
  'hasRefill' : boolean,
  'successRate' : bigint,
  'name' : string,
  'deliveryTimeHours' : bigint,
  'platform' : Platform,
  'isActive' : boolean,
  'recommendedPrice' : bigint,
  'retentionScore' : bigint,
  'category' : string,
  'qualityRating' : bigint,
  'providerId' : [] | [bigint],
  'minQuantity' : bigint,
  'baseCost' : bigint,
}
export type ServiceSort = { 'best' : null } |
  { 'cheapest' : null } |
  { 'fastest' : null };
export interface ServiceStat {
  'name' : string,
  'serviceId' : bigint,
  'totalRevenue' : number,
  'unitsSold' : bigint,
  'profitMarginPercent' : number,
}
export interface ServiceTierPublic {
  'id' : bigint,
  'features' : Array<string>,
  'displayName' : string,
  'name' : TierName,
  'marginMultiplier' : number,
  'description' : string,
  'deliveryMultiplier' : number,
  'isActive' : boolean,
  'priorityProcessing' : boolean,
  'refillGuarantee' : boolean,
  'supportLevel' : SupportLevel,
  'badge' : string,
}
export interface SubscriptionPlan {
  'id' : SubscriptionPlanId,
  'features' : Array<string>,
  'name' : string,
  'tier' : PlanTier,
  'discountPercent' : bigint,
  'priceMonthly' : bigint,
}
export type SubscriptionPlanId = bigint;
export type SupportLevel = { 'dedicated' : null } |
  { 'priority' : null } |
  { 'standard' : null };
export interface SystemLog {
  'id' : bigint,
  'status' : LogStatus,
  'action' : string,
  'actorId' : string,
  'timestamp' : bigint,
  'targetType' : string,
  'details' : string,
  'targetId' : string,
}
export type TicketCategory = { 'order' : null } |
  { 'billing' : null } |
  { 'technical' : null } |
  { 'general' : null };
export type TicketId = bigint;
export interface TicketMessage {
  'id' : TicketMessageId,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'ticketId' : TicketId,
  'message' : string,
  'isAdminReply' : boolean,
}
export type TicketMessageId = bigint;
export interface TicketPublic {
  'id' : TicketId,
  'status' : TicketStatus,
  'subject' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'lastUpdatedAt' : Timestamp,
  'category' : TicketCategory,
}
export type TicketStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'in_progress' : null } |
  { 'open' : null };
export interface TicketWithMessages {
  'ticket' : {
    'id' : TicketId,
    'status' : TicketStatus,
    'subject' : string,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'lastUpdatedAt' : Timestamp,
    'category' : TicketCategory,
  },
  'messages' : Array<TicketMessage>,
}
export type TierName = { 'premium' : null } |
  { 'recommended' : null } |
  { 'basic' : null };
export type Timestamp = bigint;
export interface TopServiceStat {
  'revenue' : number,
  'name' : string,
  'serviceId' : bigint,
  'unitsSold' : bigint,
}
export interface Transaction {
  'id' : TransactionId,
  'status' : TransactionStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'txType' : TransactionType,
  'amount' : bigint,
}
export type TransactionId = bigint;
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TransactionType = { 'credit' : null } |
  { 'debit' : null } |
  { 'refund' : null };
export type UserId = Principal;
export interface UserLevelPublic {
  'id' : bigint,
  'maxSpend' : bigint,
  'displayName' : string,
  'cashbackPercent' : number,
  'minSpend' : bigint,
  'levelName' : LevelName,
  'badge' : string,
  'perks' : Array<string>,
}
export interface UserPublic {
  'id' : UserId,
  'username' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'avatar' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null };
export interface UserStats {
  'totalOrders' : bigint,
  'totalSpend' : bigint,
  'completedOrders' : bigint,
  'activeOrders' : bigint,
}
export interface UserSubscriptionPublic {
  'endDate' : Timestamp,
  'planId' : SubscriptionPlanId,
  'userId' : UserId,
  'isActive' : boolean,
  'autoRenew' : boolean,
  'startDate' : Timestamp,
}
export interface WalletRewardPublic {
  'id' : bigint,
  'percentageAmount' : number,
  'isActive' : boolean,
  'rewardType' : RewardType,
  'frequency' : string,
  'amount' : bigint,
}
export interface _SERVICE {
  'adminAddBundle' : ActorMethod<
    [
      string,
      string,
      Array<BundleService>,
      bigint,
      bigint,
      bigint,
      boolean,
      string,
      string,
    ],
    BundlePublic
  >,
  'adminAddCoupon' : ActorMethod<
    [string, number, bigint, Timestamp, Array<ServiceId>],
    CouponPublic
  >,
  'adminAddCurrency' : ActorMethod<
    [string, string, string, string, number],
    CurrencyPublic
  >,
  'adminAddFunds' : ActorMethod<[UserId, bigint, string], Transaction>,
  'adminAddPricingRule' : ActorMethod<
    [Array<ServiceId>, number, number, number, Array<[string, number]>],
    AdminPricingRulePublic
  >,
  'adminAddProvider' : ActorMethod<
    [string, string, string, number, bigint],
    ProviderPublic
  >,
  'adminAddService' : ActorMethod<
    [string, Platform, bigint, bigint, bigint, bigint, boolean, bigint, bigint],
    ServicePublic
  >,
  'adminAdjustUserWallet' : ActorMethod<
    [Principal, number, string, boolean],
    undefined
  >,
  'adminApproveReview' : ActorMethod<[bigint, bigint], undefined>,
  'adminBanUser' : ActorMethod<[Principal, string], undefined>,
  'adminBatchUpdateServicePrices' : ActorMethod<
    [Array<bigint>, number],
    undefined
  >,
  'adminCancelOrder' : ActorMethod<[bigint, string], undefined>,
  'adminGetAllOrders' : ActorMethod<
    [[] | [string], bigint, bigint],
    Array<OrderPublic>
  >,
  'adminGetAllUsers' : ActorMethod<
    [[] | [string], [] | [string], bigint, bigint],
    Array<UserPublic>
  >,
  'adminGetConfig' : ActorMethod<[], AdminConfig>,
  'adminGetDashboardStats' : ActorMethod<[], DashboardStats>,
  'adminGetFraudAlerts' : ActorMethod<
    [[] | [boolean], [] | [bigint], bigint, bigint],
    Array<FraudAlertPublic>
  >,
  'adminGetLogs' : ActorMethod<
    [[] | [string], bigint, bigint],
    Array<SystemLog>
  >,
  'adminGetPricingRules' : ActorMethod<[], Array<AdminPricingRulePublic>>,
  'adminGetProviders' : ActorMethod<[], Array<ProviderPublic>>,
  'adminGetServiceStats' : ActorMethod<[], Array<ServiceStat>>,
  'adminGetWalletRewards' : ActorMethod<[], Array<WalletRewardPublic>>,
  'adminListOrders' : ActorMethod<[], Array<OrderPublic>>,
  'adminListTickets' : ActorMethod<[], Array<TicketPublic>>,
  'adminListUsers' : ActorMethod<[], Array<UserPublic>>,
  'adminReplyToTicket' : ActorMethod<[TicketId, string], TicketMessage>,
  'adminResolveFraudAlert' : ActorMethod<[bigint, string], undefined>,
  'adminSetUserRole' : ActorMethod<[UserId, UserRole], undefined>,
  'adminUpdateBundle' : ActorMethod<
    [bigint, [] | [string], [] | [bigint], [] | [boolean]],
    boolean
  >,
  'adminUpdateConfig' : ActorMethod<[AdminConfig], undefined>,
  'adminUpdateExchangeRate' : ActorMethod<[string, number], boolean>,
  'adminUpdateOrderManual' : ActorMethod<
    [bigint, [] | [string], [] | [number], [] | [bigint], string],
    undefined
  >,
  'adminUpdateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'adminUpdateProvider' : ActorMethod<
    [bigint, [] | [string], [] | [number], [] | [bigint]],
    undefined
  >,
  'adminUpdateService' : ActorMethod<
    [ServiceId, string, bigint, boolean],
    undefined
  >,
  'adminUpdateServiceVisibility' : ActorMethod<[bigint, boolean], undefined>,
  'adminUpdateTier' : ActorMethod<
    [
      bigint,
      [] | [number],
      [] | [number],
      [] | [Array<string>],
      [] | [boolean],
    ],
    boolean
  >,
  'adminUpdateWalletReward' : ActorMethod<
    [bigint, [] | [bigint], [] | [number], [] | [boolean]],
    undefined
  >,
  'calculateTierPrice' : ActorMethod<[bigint, bigint], [] | [bigint]>,
  'cancelMySubscription' : ActorMethod<[], undefined>,
  'cancelOrder' : ActorMethod<[OrderId], undefined>,
  'claimDailyLoginReward' : ActorMethod<[], bigint>,
  'closeMyTicket' : ActorMethod<[TicketId], undefined>,
  'convertPrice' : ActorMethod<[bigint, string], [] | [number]>,
  'createReferral' : ActorMethod<[Principal], ReferralPublic>,
  'createTicket' : ActorMethod<[string, TicketCategory], TicketPublic>,
  'generateApiKey' : ActorMethod<[string], ApiKeyPublic>,
  'getAllApprovedReviews' : ActorMethod<[bigint], Array<ReviewPublic>>,
  'getBundle' : ActorMethod<[bigint], [] | [BundlePublic]>,
  'getMyBalance' : ActorMethod<[], bigint>,
  'getMyEngagementHistory' : ActorMethod<[bigint], Array<EngagementLog>>,
  'getMyLevel' : ActorMethod<[], [] | [UserLevelPublic]>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationPublic>>,
  'getMyOrders' : ActorMethod<[], Array<OrderPublic>>,
  'getMyProfile' : ActorMethod<[], UserPublic>,
  'getMyReferrals' : ActorMethod<[], Array<ReferralPublic>>,
  'getMyStats' : ActorMethod<[], UserStats>,
  'getMySubscription' : ActorMethod<[], [] | [UserSubscriptionPublic]>,
  'getMyTickets' : ActorMethod<[], Array<TicketPublic>>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getOrderById' : ActorMethod<[OrderId], [] | [OrderPublic]>,
  'getServicePricing' : ActorMethod<
    [bigint, ServiceId],
    [number, number, number]
  >,
  'getServiceReviews' : ActorMethod<[ServiceId, bigint], Array<ReviewPublic>>,
  'getServicesByPlatform' : ActorMethod<[Platform], Array<ServicePublic>>,
  'getServicesSorted' : ActorMethod<[ServiceSort], Array<ServicePublic>>,
  'getSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getTicketDetail' : ActorMethod<[TicketId], [] | [TicketWithMessages]>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'listBundles' : ActorMethod<[], Array<BundlePublic>>,
  'listCurrencies' : ActorMethod<[], Array<CurrencyPublic>>,
  'listMyApiKeys' : ActorMethod<[], Array<ApiKeyPublic>>,
  'listMyCoupons' : ActorMethod<[], Array<CouponPublic>>,
  'listServiceTiers' : ActorMethod<[], Array<ServiceTierPublic>>,
  'listServices' : ActorMethod<[], Array<ServicePublic>>,
  'listUserLevels' : ActorMethod<[], Array<UserLevelPublic>>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], OrderPublic>,
  'registerUser' : ActorMethod<[string, string], UserPublic>,
  'replyToTicket' : ActorMethod<[TicketId, string], TicketMessage>,
  'revokeApiKey' : ActorMethod<[ApiKeyId], undefined>,
  'searchServices' : ActorMethod<[string], Array<ServicePublic>>,
  'spinWheelReward' : ActorMethod<[], bigint>,
  'submitReview' : ActorMethod<[ServiceId, bigint, string], ReviewPublic>,
  'subscribeToPlan' : ActorMethod<
    [SubscriptionPlanId, boolean],
    UserSubscriptionPublic
  >,
  'updateMyProfile' : ActorMethod<[string, string, [] | [string]], UserPublic>,
  'validateCoupon' : ActorMethod<[string, ServiceId], [] | [number]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];